greet = 'Привет, это бот написанный для игры в пиздабола (автор Pajojda_1)'
menu = 'Главное меню'
start_lobby = 'Вы создали лобби. Текущий код приглашения: {tok}'
gen_exit = 'exit'
login_lobby = 'Введите код приглашения для входа в лобби'
statistics = 'Ваша статистика:'
lobby_successfully = 'Вы успешно вошли в лобби игрока {name}'
exit_player = 'Игрок {name} покинул лобби'
start_game = "Игрок {name} начал игру!"